### ISSUE TITLE
[debian] Split libperfsonar-perl into smaller libs

### ISSUE THREAD

**Issue by tonin** [perfsonar/perl-shared#11]
The RPM specfile now defines 5 different libperfsonar packages:
- libperfsonar-perl
- libperfsonar-sls-perl
- libperfsonar-esmond-perl
- libperfsonar-toolkit-perl
- libperfsonar-regulartesting-perl

We should do the same with the debian package.

**Comment by vvidic** [comment]
Ok, I'll take a look...

**Comment by vvidic** [comment]
Debian branches are updated with the new lib names with a few notes:
- there is only one source package now so the Jenkins build needs to be updated
- all the libs are in /usr/share/perl5, not sure if we need to put anything in /usr/lib/perfsonar
- dependencies in other packages will need to be checked

**Comment by tonin** [comment]
The new lib packages are available in the snapshot repos and can be tested with the other 3.5.1 RC packages.

**Comment by arlake228** [comment]
Can this issue be closed?

**Comment by tonin** [comment]
Yes, this is done.
