### ISSUE TITLE
Missing semicolon in Result.pm

### ISSUE THREAD

**Issue by vvidic** [perfsonar/perl-shared#13]
Not sure if this file is used at all but the second line is missing a semicolon:

    package perfSONAR_PS::NPToolkit::DataService::Result;
    use fields qw(results)
    
    use strict;

[Result.pm](https://github.com/perfsonar/perl-shared/blob/master/lib/perfSONAR_PS/NPToolkit/DataService/Result.pm)

**Comment by mfeit-internet2** [comment]
As part of the build/package process, anything written in Perl really needs to be passed through `perl -c`, which would have caught this.

**Comment by apertome** [comment]
Good catch -- looking around, this code is not used for anything. I intended to use it, but apparently never integrated it.  I'm removing the file.
