### ISSUE TITLE
Esmond client libraries to parse credentials from a local file/folder

### ISSUE THREAD

**Issue by igarny** [perfsonar/perl-shared#15]
Hi Andy,

It would be useful to have the ability to define a file or a folder with Esmond credentials.
The idea is to allow for great flexibility with mesh configuration and with pSscheduler, where exposing the credential information is not a good idea.

It would also be a great relief for automation, since the content of these files is static and there is no need to parse and preserve changes of other running services (regular_testing)

Best regards,
Ivan

**Comment by arlake228** [comment]
psconfig will allow this functionality through the use of transform scripts, closing since those are implemented.
