### ISSUE TITLE
Port Debian patches upstream when possible

### ISSUE THREAD

**Issue by tonin** [perfsonar/perl-shared#46]
I think we can easily port upstream some Debian packages patches so that we simplify the whole packaging.  These should probably be considered for inclusion in upstream:
 - https://github.com/perfsonar/perl-shared/blob/debian/jessie/debian/patches/ntp-config.diff
 - https://github.com/perfsonar/perl-shared/blob/debian/jessie/debian/patches/owamp-stop.diff

The other patches should be reviewed too and added if possible.

**Comment by tonin** [comment]
@vvidic Can you also have a look at merging the `ntp-config.diff` patch upstream by testing the existence of the `step-tickers` file?

**Comment by vvidic** [comment]
I don't think `step-tickers` file is used on the Debian side so I guest there should be no harm if we add it. Will check once more and create a PR.

**Comment by vvidic** [comment]
The problem was nonexisting directory `/etc/ntp` on the Debian side. I've added this directory to `perfsonar-toolkit-ntp` so writing `step-tickers` works now and `ntp-config.diff` patch is removed.

**Comment by tonin** [comment]
Thanks!  Can we also then remove https://github.com/perfsonar/toolkit/blob/debian/jessie/debian/patches/debian-ntp.diff  I'm not sure what's intended with the different `-e -a -s` flags.

**Comment by vvidic** [comment]
You are right, `/etc/ntp` exist now so the `configure_ntpd` should also work without patching. Dropping this patch too.

**Comment by tonin** [comment]
I think this is all we can port upstream at the moment.
