### ISSUE TITLE
Update Debian packaging to latest dependency changes

### ISSUE THREAD

**Issue by tonin** [perfsonar/perl-shared#49]
There has been quite a lot of perl library dependency changes following the addition of the psconfig libraries and the replacement of the LWP modules by the Mojo ones.  We need to review that in the Debian packages too.

**Comment by vvidic** [comment]
Quite strange, can't get some test to run properly:
```
#   Failed test at t/client-psconfig-addressclasses.t line 346.
#          got: '10'
#     expected: '0'
# Looks like you failed 1 test of 523.
t/client-psconfig-addressclasses.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/523 subtests 
t/client-psconfig-circuits.t ........ ok
t/client-psconfig-contexts.t ........ ok
t/client-psconfig-disjoint.t ........ ok

#   Failed test at t/client-psconfig-labels.t line 219.
#          got: '2'
#     expected: '0'
# Looks like you failed 1 test of 369.
t/client-psconfig-labels.t .......... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/369 subtests 
t/client-psconfig-list.t ............ ok

#   Failed test at t/client-psconfig-mesh.t line 84.
#          got: '1'
#     expected: '0'
# Looks like you failed 1 test of 60.
t/client-psconfig-mesh.t ............ 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/60 subtests 

#   Failed test at t/client-psconfig-noagent.t line 123.
#          got: '1'
#     expected: '0'
# Looks like you failed 1 test of 53.
t/client-psconfig-noagent.t ......... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/53 subtests 

#   Failed test at t/client-psconfig-taskgenerator.t line 181.
#          got: 'Q5N6OaenL2+IPB9WVK+PQw'
#     expected: 'UwWSmNRYrKPw0UKuTMXGbg'

#   Failed test at t/client-psconfig-taskgenerator.t line 197.
#          got: 'QBNMDnJZOfxP3ei9ZpFrcg'
#     expected: 'qWC5b7x0212uHxD1z5LTtg'
# Looks like you failed 2 tests of 70.
t/client-psconfig-taskgenerator.t ... 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/70 subtests 
Can't use an undefined value as a HASH reference at t/client-psconfig-template.t line 198.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 2 just after 34.
t/client-psconfig-template.t ........ 
Dubious, test returned 2 (wstat 512, 0x200)
All 34 subtests passed 

#   Failed test at t/client-psconfig.t line 597.
#          got: '2'
#     expected: '0'
# {}
# Looks like you failed 1 test of 538.
t/client-psconfig.t ................. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/538 subtests 
```
Perhaps @arlake228 has an idea what could be wrong here?

**Comment by arlake228** [comment]
It looks like all of them except for the ones in client-psconfig-taskgenerator are because JSON is not validating against the JSON schema. Might want to check you have the perl module JSON::Validator installed. I don't have easy access to a debian host at the moment to test, but doing a dump of the result of the call to validate should tell what it doesn't like. 

For task-generator, it doesn't like the checksum of the JSON produced. Again a dump of the $psched_task object should help show if there is something in the JSON or missing from the JSON that shouldn't be.

**Comment by vvidic** [comment]
On Thu, Feb 22, 2018 at 01:39:15PM +0000, Andrew R. Lake wrote:
> It looks like all of them except for the ones in
> client-psconfig-taskgenerator are because JSON is not validating
> against the JSON schema. Might want to check you have the perl module
> JSON::Validator installed. I don't have easy access to a debian host
> at the moment to test, but doing a dump of the result of the call to
> validate should tell what it doesn't like. 
> 
> For task-generator, it doesn't like the checksum of the JSON produced.
> Again a dump of the $psched_task object should help show if there is
> something in the JSON or missing from the JSON that shouldn't be. 

JSON::Validator is installed but is also failing some of it's own unit
tests.  Maybe this is causing failures in perl-shared too.  Will need
to investigate a bit...

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by vvidic** [comment]
Ok, JSON::Validator needed a newer version of Test::Simple to run tests without errors and perl-shared needed a jq. The tests are passing now so I will update the deps.

**Comment by vvidic** [comment]
Mojo added to perl-shared, will check the Jenkins build.

**Comment by vvidic** [comment]
Jenkins looks good so closing this now.
