### ISSUE TITLE
Sys::MemInfo is not available in Debian

### ISSUE THREAD

**Issue by tonin** [perfsonar/perl-shared#5]
`Sys::MemInfo` is not available under Debian wheezy nor jessie.  We should either port it back (it is available in stretch) or replace it with a call to `get_health_info()` as done at https://github.com/perfsonar/ls-registration-daemon/commit/e6a40ec0aa408f47863537199d4a7381606b2da1

**Comment by tonin** [comment]
@vvidic Did you have this Sys::MemInfo module already prepared in the minor-packages repo?

**Comment by vvidic** [comment]
I found it exists in testing so I added that to https://github.com/perfsonar/minor-packages/commit/1ce224f9500dab6c8acc85cb434bc6760bac576c

**Comment by tonin** [comment]
Thanks, libsys-meminfo-perl 0.98 is now in both perfsonar-wheezy-snapshot and perfsonar-jessie-snapshot.
