### ISSUE TITLE
Remove bwctl support

### ISSUE THREAD

**Issue by tonin** [perfsonar/perl-shared#51]
Remove all bwctl hard references in the perl libraries so that we can remove any dependency to bwctl with 4.1.

**Comment by arlake228** [comment]
References removed in master to the extent they can be in 4.1. If you do a grep, the ones that remain are mostly in RegularTesting. The Toolkit UI still uses this library for generating regular tests then converts it when it is done to psconfig. 

Tested locally in rpm with toolkit changes and seems to be working. Assigning to antoine to make sure they are merged in Debian.

**Comment by arlake228** [comment]
If done for Debian, we can close.

**Comment by vvidic** [comment]
Already removed from Debian packages, closing.
